name = "TerraFirmaMon"
author = "n0es"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc1169170855f0216f71fb824702d6b5883be548463e7e4cfd0f46e6f9518f87"

[versions]
minecraft = "1.20.1"
forge = "47.4.13"
