name = "TerraFirmaMon"
author = "n0es"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb0fc433f0c9fa271313c5b0e9c600ddc340f8d4682e493d72ccf4015f8851a4"

[versions]
minecraft = "1.20.1"
forge = "47.4.13"
