name = "TerraFirmaMon"
author = "n0es"
version = "1.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9ccde2ffa4812b95b01bcd5a37f3e70932053515c12d0590c23fdfd9c99fde7"

[versions]
minecraft = "1.20.1"
forge = "47.4.13"
